<template>
    <output
        aria-label="Loading"
        :class="[
            'animate-spin',
            'rounded-full',
            'h-4',
            'w-4',
            'border-2',
            'border-border-primary-brand-default',
            'border-t-transparent',
        ]"
    />
</template>